name: test-project
on:
  push: {}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Get code
    - uses: actions/checkcout@v3
    - name: Install NodeJs
    - uses: actions/setup-node@v3
    - name: Install dependencies
    - uses: npm ci
    - name: run tests
    - uses: npm test